### ISSUE TITLE
Not Working 😢 

### ISSUE THREAD

**Issue by karimawii** [Kiyoshi-23/Hide-Menu-Icons#1]
![image](https://user-images.githubusercontent.com/69881381/155902181-72dd6eb8-513d-487d-9881-00aa1f48b107.png)
![image](https://user-images.githubusercontent.com/69881381/155904607-567ce697-3be2-4d0a-89f3-3574fae4f8ad.png)
![image](https://user-images.githubusercontent.com/69881381/155902194-d18c3723-ffec-452c-b3f7-553a09d0e4f7.png)
![image](https://user-images.githubusercontent.com/69881381/155902218-c027f07e-a482-4955-af79-8525f8e0873e.png)

**Comment by Kiyoshi-23** [comment]
This isn't even finished yet. Please be patient as this will be finished in the next month or 2. 

~Best, Kiyoshi
